ImgSize:
- 1088
- 608
K: 128
arch: dla_34
batch_size: 12
bias: 150
cat_spec_wh: false
chunk_sizes:
- 6
- 6
conf_thres: 0.4
data_cfg: ../FairMot/lib/cfg/data.json
data_dir: /data/yfzhang/MOT/JDE
dataset: jde
debug_dir: /datanew/hwb/FairMOT-master/FairMot/lib/../../exp/mot/default/debug
dense_wh: false
det_thres: 0.3
dir_name: '11'
down_ratio: 4
exp_dir: /datanew/hwb/FairMOT-master/FairMot/lib/../../exp/mot
exp_id: default
fix_res: true
gpus:
- 0
- 1
gpus_str: 0, 1
head_conv: 256
heads:
  hm: 1
  id: 512
  reg: 2
  wh: 2
hide_data_time: false
hm_weight: 1
id_loss: ce
id_weight: 1
img_size:
- 1088
- 608
input_h: 608
input_res: 1088
input_video: "/datanew/hwb/data/\u8DB3\u7403\u89C6\u9891/test.MP4"
input_w: 1088
keep_res: false
load_model: /datanew/hwb/data/Tracking/FairMOT/pretrained_models/all_dla34.pth
lr: 0.0001
lr_step:
- 20
- 27
master_batch_size: 6
mean:
- 0.408
- 0.447
- 0.47
metric: loss
min_box_area: 200
mse_loss: false
nID: 14455
nms_thres: 0.4
norm_wh: false
not_cuda_benchmark: false
not_prefetch_test: false
not_reg_offset: false
num_classes: 1
num_epochs: 30
num_iters: -1
num_stacks: 1
num_workers: 8
off_weight: 1
output_format: video
output_h: 152
output_res: 272
output_root: ../results
output_w: 272
pad: 31
print_iter: 0
radius: 10
reg_loss: l1
reg_offset: true
reid_dim: 512
resume: false
root_dir: /datanew/hwb/FairMOT-master/FairMot/lib/../..
save_all: false
save_dir: /datanew/hwb/FairMOT-master/FairMot/lib/../../exp/mot/default
seed: 317
std:
- 0.289
- 0.274
- 0.278
task: mot
test: false
test_mot15: false
test_mot16: false
test_mot17: false
test_mot20: false
track_buffer: 30
trainval: false
val_intervals: 5
val_mot15: false
val_mot16: false
val_mot17: false
val_mot20: false
vis_thresh: 0.4
wh_weight: 0.1
