DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  SAMPLER: softmax_triplet
DATASETS:
  NAMES: market1501
  ROOT_DIR: /datanew/hwb/Re-ID_models/reid-strong-baseline-master/data
INPUT:
  PADDING: 10
  PIXEL_MEAN:
  - 0.485
  - 0.456
  - 0.406
  PIXEL_STD:
  - 0.229
  - 0.224
  - 0.225
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST:
  - 256
  - 128
  SIZE_TRAIN:
  - 256
  - 128
MODEL:
  DEVICE: cuda
  DEVICE_ID: '0'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: triplet_center
  NAME: resnet50
  NECK: bnneck
  PRETRAIN_CHOICE: imagenet
  PRETRAIN_PATH: /datanew/hwb/.torch/models/resnet50-19c8e357.pth
OUTPUT_DIR: /datanew/hwb/Re-ID_models/reid-strong-baseline-master/weights
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 40
  CLUSTER_MARGIN: 0.3
  EVAL_PERIOD: 40
  GAMMA: 0.1
  IMS_PER_BATCH: 64
  LOG_PERIOD: 20
  MARGIN: 0.3
  MAX_EPOCHS: 120
  MOMENTUM: 0.9
  OPTIMIZER_NAME: Adam
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_K: 2
  RANGE_LOSS_WEIGHT: 1
  RANGE_MARGIN: 0.3
  STEPS:
  - 40
  - 70
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  FEAT_NORM: 'yes'
  IMS_PER_BATCH: 128
  NECK_FEAT: after
  RE_RANKING: 'no'
  WEIGHT: /datanew/hwb/Re-ID_models/reid-strong-baseline-master/weights/resnet50_model_120.pth
